nelmio_api_doc:
    documentation:
        info:
            title: DiabCare API
            description: Documentation de l'API backend pour la plateforme DiabCare
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)
