import { useEffect, useRef } from 'react';
import { ConversationThread, Message, MessageAttachment } from '../types';
import { AttachmentPreview } from './AttachmentPreview';
import {
    DeleteIcon,
    DoubleCheckIcon,
    SingleCheckIcon,
    BackIcon,
} from "@/react/features/clinician/messages/components/MessageIcons";
import { usePresence } from '../hooks/usePresence';

interface MessageListProps {
    thread: ConversationThread;
    onDeleteMessage: (messageId: string) => void;
    onBack?: () => void;
}

export function MessageList({
                                thread,
                                onDeleteMessage,
                                onBack,
                            }: MessageListProps) {
    const messagesContainerRef = useRef<HTMLDivElement>(null);

    const isOnline = usePresence(thread.participantId);

    /*
     * Scroll automatique vers le dernier message
     */
    useEffect(() => {
        const container = messagesContainerRef.current;

        if (!container) {
            return;
        }

        requestAnimationFrame(() => {
            container.scrollTo({
                top: container.scrollHeight,
                behavior: 'smooth',
            });
        });
    }, [thread.messages, thread.id]);

    return (
        <div className="message-thread-wrapper">

            {/* =====================================================
                EN-TÊTE DE LA DISCUSSION
            ===================================================== */}

            <div className="message-thread__header">

                {onBack && (
                    <button
                        type="button"
                        className="icon-button message-thread__back-btn"
                        onClick={onBack}
                        title="Retour"
                        aria-label="Retour"
                    >
                        <BackIcon />
                    </button>
                )}

                <div className="message-thread__participant-info">

                    <div className="message-thread__avatar-placeholder">
                        {thread.participant
                            .charAt(0)
                            .toUpperCase()}
                    </div>

                    <div>
                        <h3>{thread.participant}</h3>

                        <span
                            className={`message-thread__status ${
                                isOnline
                                    ? 'message-thread__status--online'
                                    : 'message-thread__status--offline'
                            }`}
                        >
                            {isOnline
                                ? 'En ligne'
                                : 'Hors ligne'}
                        </span>
                    </div>

                </div>
            </div>

            {/* =====================================================
                LISTE DES MESSAGES
            ===================================================== */}

            <div
                className="message-thread__messages"
                ref={messagesContainerRef}
            >

                {/*
                 * IMPORTANT :
                 *
                 * Ce conteneur prend au minimum toute la hauteur
                 * disponible et pousse les messages vers le bas.
                 */}
                <div className="message-thread__messages-content">

                    {thread.messages.map(
                        (
                            msg: Message,
                            index: number
                        ) => {

                            const isMine =
                                msg.emetteur === 'moi';

                            const prevMsg =
                                thread.messages[index - 1];

                            const showDateSeparator =
                                !prevMsg ||
                                prevMsg.date !== msg.date;

                            const hasAttachment =
                                !!msg.attachments &&
                                msg.attachments.length > 0;

                            const isAutoGeneratedText =
                                msg.contenu.startsWith(
                                    'Fichier:'
                                );

                            const shouldShowContent =
                                !(
                                    hasAttachment &&
                                    isAutoGeneratedText
                                );

                            return (
                                <div
                                    key={msg.id}
                                    className="message-item-wrapper"
                                >

                                    {/* =========================
                                        SÉPARATEUR DE DATE
                                    ========================= */}

                                    {showDateSeparator && (
                                        <div className="message-date-separator">
                                            <span>
                                                {new Date(
                                                    msg.date
                                                ).toLocaleDateString()}
                                            </span>
                                        </div>
                                    )}

                                    {/* =========================
                                        BULLE DU MESSAGE
                                    ========================= */}

                                    <div
                                        className={`message-bubble ${
                                            isMine
                                                ? 'message-bubble--mine'
                                                : 'message-bubble--other'
                                        }`}
                                    >

                                        {/* =====================
                                            SUPPRESSION
                                        ===================== */}

                                        <button
                                            type="button"
                                            className="message-bubble__delete-btn"
                                            onClick={() =>
                                                onDeleteMessage(
                                                    msg.id
                                                )
                                            }
                                            title="Supprimer"
                                            aria-label="Supprimer le message"
                                        >
                                            <DeleteIcon />
                                        </button>

                                        {/* =====================
                                            PIÈCES JOINTES
                                        ===================== */}

                                        {msg.attachments?.map(
                                            (
                                                attachment: MessageAttachment
                                            ) => (
                                                <div
                                                    key={
                                                        attachment.id
                                                    }
                                                    className="message-bubble__attachment"
                                                >
                                                    <AttachmentPreview
                                                        attachment={
                                                            attachment
                                                        }
                                                    />
                                                </div>
                                            )
                                        )}

                                        {/* =====================
                                            CONTENU TEXTE
                                        ===================== */}

                                        {shouldShowContent &&
                                            msg.contenu && (
                                                <p className="message-bubble__content">
                                                    {msg.contenu}
                                                </p>
                                            )}

                                        {/* =====================
                                            MÉTADONNÉES
                                        ===================== */}

                                        <div className="message-bubble__meta">

                                            <span className="message-bubble__time">
                                                {new Date(
                                                    msg.date
                                                ).toLocaleTimeString(
                                                    [],
                                                    {
                                                        hour: '2-digit',
                                                        minute: '2-digit',
                                                    }
                                                )}
                                            </span>

                                            {isMine && (
                                                <span className="message-bubble__status-icon">
                                                    {msg.status ===
                                                    'read' ? (
                                                        <DoubleCheckIcon />
                                                    ) : (
                                                        <SingleCheckIcon />
                                                    )}
                                                </span>
                                            )}

                                        </div>
                                    </div>
                                </div>
                            );
                        }
                    )}

                </div>
            </div>
        </div>
    );
}
