<?php

namespace App\Entity\Notification;

enum NotificationType: string
{
    case MEDICATION_REMINDER = 'MEDICATION_REMINDER';
    case APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER';
    case MEASUREMENT_REMINDER = 'MEASUREMENT_REMINDER';
    case MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
    case PRESCRIPTION_UPDATED = 'PRESCRIPTION_UPDATED';
    case SYSTEM_ALERT = 'SYSTEM_ALERT';
}
